
providers = ["node"]

[phases.install]
cmds = ["npm install -g corepack", "corepack enable", "corepack prepare pnpm@9.5.0 --activate", "pnpm install"]

[phases.build]
cmd = ["pnpm build"]

[phases.start]
cmd = ["pnpm start"]
